#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080   # Порт, на котором будет работать приложение

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb   # твоя база (замени на имя, которое создал)
    username: postgres   # имя пользователя БД
    password: postgres   # пароль (замени на свой)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # проверяет, что структура БД соответствует сущностям (мы используем Liquibase, поэтому update/create тут НЕ нужно)
    show-sql: true         # выводит SQL в консоль (удобно для дебага)
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml  # путь к master-файлу с миграциями
    enabled: true

# JWT-конфигурация (значения подставишь свои)
jwt:
  secret: "superSecretKeyForJWT123"   # длинный секретный ключ для подписи токенов
  expiration: 3600000   # время жизни токена в миллисекундах (1 час)

# Swagger (Springdoc OpenAPI)
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
