package com.example.bankcards.exception;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Standardized error response returned by the BankCards REST API.
 * <p>
 * Represents the structure of all error messages sent by the backend
 * when an exception is thrown. Follows a simplified form of the
 * <a href="https://datatracker.ietf.org/doc/html/rfc7807">RFC 7807 Problem Details</a> specification.
 * </p>
 *
 * <p>Typical JSON example:</p>
 * <pre>{@code
 * {
 *   "timestamp": "2025-10-09T12:34:56.789",
 *   "status": 404,
 *   "error": "Not Found",
 *   "message": "Card with id=10 not found",
 *   "path": "/api/cards/10"
 * }
 * }</pre>
 *
 * <p>
 * This response model is automatically generated by the global exception handler
 * ({@code GlobalExceptionHandler}) for all application-level errors.
 * </p>
 *
 * @author Konstantin Sakhokiia
 * @since 1.0
 */
@Data
@AllArgsConstructor
public class ApiErrorResponse {

    /**
     * The moment the error occurred (server time).
     */
    private LocalDateTime timestamp;

    /**
     * HTTP status code associated with the error (e.g. 404, 401, 422).
     */
    private int status;

    /**
     * Short textual representation of the error (e.g. "Not Found", "Unauthorized").
     */
    private String error;

    /**
     * Detailed human-readable message explaining the reason of failure.
     */
    private String message;

    /**
     * Request path (URI) where the error occurred.
     */
    private String path;
}
